// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBOrqYjM7UZjnEuHLQQKDm-rE7ooNsngo',
    appId: '1:623067127966:android:eac303a7f5d13911351b8f',
    messagingSenderId: '623067127966',
    projectId: 'agripedia-18ccd',
    databaseURL: 'https://agripedia-18ccd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agripedia-18ccd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhrzmjuXGGVgiqe6jY_Dfs4DbVo9LJLP0',
    appId: '1:623067127966:ios:20dca8568e90b04e351b8f',
    messagingSenderId: '623067127966',
    projectId: 'agripedia-18ccd',
    databaseURL: 'https://agripedia-18ccd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agripedia-18ccd.appspot.com',
    iosBundleId: 'com.example.agripedia.agripedia',
  );
}
