// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZtxHczuQ7xjzp-PZizXpumyvQAeBR2cs',
    appId: '1:432764405515:android:6f666f9c13978904b0840e',
    messagingSenderId: '432764405515',
    projectId: 'agripedia-c5439',
    databaseURL: 'https://agripedia-c5439-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agripedia-c5439.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeYJOjcDe2DKv8Kt3SyRC5VTpnxpGePHM',
    appId: '1:432764405515:ios:1aa5d9f3f2fdd8c3b0840e',
    messagingSenderId: '432764405515',
    projectId: 'agripedia-c5439',
    databaseURL: 'https://agripedia-c5439-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agripedia-c5439.appspot.com',
    iosBundleId: 'com.example.agripedia.agripedia',
  );
}
